version: '3.0'

services:
  db:
    platform: linux/amd64
    image: mysql:latest
    container_name: mysql_db
    env_file:
      - ./.env
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./databases/:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
