version: '3'

services:
  db_aula:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./databases/:/docker-entrypoint-initdb.d/
      - ./data/:/var/lib/mysql